In [1]:
import re

In [2]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    text = f.read()
    text = text.replace('\ufeff', '') # убираем первый невидимый символ
    text = re.sub(r'[^А-я ]', '', text) # убираем все недопустимые символы

In [3]:
text

'Вы  лучший ответ на проблемы которые возникли в понедельникДумайте позитивно и верьте в свою способность достигать отличных результатовЕсли вы смогли в понедельник подняться с постели значит вы супер герой'

In [4]:
len(text)

205

In [5]:
num_characters = 34 #33 буквы + пробел

In [6]:
import keras
from keras.preprocessing.text import Tokenizer

In [7]:
num_characters = 34 #33 буквы + пробел
tokenizer = Tokenizer(num_words=num_characters, char_level=True)

In [8]:
tokenizer.fit_on_texts(text)

In [9]:
print(tokenizer.word_index)

{' ': 1, 'о': 2, 'т': 3, 'е': 4, 'и': 5, 'в': 6, 'н': 7, 'с': 8, 'л': 9, 'п': 10, 'ь': 11, 'ы': 12, 'р': 13, 'а': 14, 'д': 15, 'у': 16, 'к': 17, 'з': 18, 'ч': 19, 'й': 20, 'м': 21, 'г': 22, 'б': 23, 'я': 24, 'ш': 25, 'ю': 26, 'х': 27}


In [10]:
inp_chars = 6
data = tokenizer.texts_to_matrix(text)

In [11]:
data[0]

array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
n = data.shape[0]-inp_chars
n # размер обучающего множества

199

In [13]:
import numpy as np

In [14]:
X = np.array([data[i:i+inp_chars, :] for i in range(n)])
Y = data[inp_chars:] #предсказание следующего символа

In [15]:
len(X)

199

In [16]:
X[0]

array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0.]])

In [17]:
Y[0]

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [18]:
from keras.layers import *
from keras.models import Sequential

In [19]:
model = Sequential()
model.add(Input((inp_chars, num_characters))) 
model.add(SimpleRNN(500, activation='tanh')) 
model.add(Dense(num_characters, activation='softmax'))
model.summary()


Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn (SimpleRNN)      (None, 500)               267500    
                                                                 
 dense (Dense)               (None, 34)                17034     
                                                                 
Total params: 284534 (1.09 MB)
Trainable params: 284534 (1.09 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')
history = model.fit(X, Y, batch_size=32, epochs=100)


Epoch 1/100


7/7 [==============================] - 2s 9ms/step - loss: 3.4331 - accuracy: 0.0704
Epoch 2/100
7/7 [==============================] - 0s 9ms/step - loss: 2.4560 - accuracy: 0.3216
Epoch 3/100
7/7 [==============================] - 0s 10ms/step - loss: 1.9127 - accuracy: 0.4774
Epoch 4/100
7/7 [==============================] - 0s 18ms/step - loss: 1.5517 - accuracy: 0.5729
Epoch 5/100
7/7 [==============================] - 0s 8ms/step - loss: 1.3007 - accuracy: 0.5678
Epoch 6/100
7/7 [==============================] - 0s 8ms/step - loss: 1.0655 - accuracy: 0.6784
Epoch 7/100
7/7 [==============================] - 0s 8ms/step - loss: 0.9045 - accuracy: 0.7638
Epoch 8/100
7/7 [==============================] - 0s 10ms/step - loss: 0.7429 - accuracy: 0.8241
Epoch 9/100
7/7 [==============================] - 0s 10ms/step - loss: 0.6872 - accuracy: 0.8191
Epoch 10/100
7/7 [==============================] - 0s 8ms/step - loss: 0.5810 - accuracy: 0.8543
Epoch 11/100
7/7 [====

In [21]:
def buildPhrase(inp_str, str_len = 50):
  for i in range(str_len):
    x = []
    for j in range(i, i+inp_chars):
      x.append(tokenizer.texts_to_matrix(inp_str[j])) # преобразуем символы в One-Hot-encoding
 
    x = np.array(x)
    inp = x.reshape(1, inp_chars, num_characters)
 
    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    d = tokenizer.index_word[pred.argmax(axis=1)[0]] # получаем ответ в символьном представлении
 
    inp_str += d # дописываем строку
 
  return inp_str

In [22]:
res = buildPhrase("утренн")
print(res)

1/1 [==============================] - 0s 24ms/step
утренновтовн  и верьте в свою способность достигать отли


# Слова

In [23]:
with open('train_data.txt', 'r', encoding='utf-8') as f:
    texts = f.read()
    texts = texts.replace('\ufeff', '') # убираем первый невидимый символ

In [24]:
maxWordsCount = 1000
tokenizer = Tokenizer(num_words=maxWordsCount, filters='!–"—#$%&amp;()*+,-./:;<=>?@[\\]^_`{|}~\t\n\r«»',
                       lower=True, split=' ', char_level=False)
tokenizer.fit_on_texts([texts])

In [25]:
dist = list(tokenizer.word_counts.items())
print(dist[:10])

[('вы', 3), ('лучший', 1), ('ответ', 1), ('на', 1), ('проблемы', 1), ('которые', 1), ('возникли', 1), ('в', 3), ('понедельник', 2), ('думайте', 1)]


In [26]:
data = tokenizer.texts_to_sequences([texts])

In [27]:
data

[[1,
  4,
  5,
  6,
  7,
  8,
  9,
  2,
  3,
  10,
  11,
  12,
  13,
  2,
  14,
  15,
  16,
  17,
  18,
  19,
  1,
  20,
  2,
  3,
  21,
  22,
  23,
  24,
  1,
  25,
  26]]

In [28]:
len(data[0])

31

In [29]:
res = keras.utils.to_categorical(data[0], num_classes=maxWordsCount)
print( res.shape )

(31, 1000)


In [30]:
inp_words = 3
n = res.shape[0]-inp_words

In [31]:
X = np.array([res[i:i+inp_words, :] for i in range(n)])
Y = res[inp_words:]

In [32]:
model = Sequential()
model.add(Input((inp_words, maxWordsCount)))
model.add(SimpleRNN(128, activation='tanh'))
model.add(Dense(maxWordsCount, activation='softmax'))
model.summary()
 
model.compile(loss='categorical_crossentropy', metrics=['accuracy'], optimizer='adam')

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 simple_rnn_1 (SimpleRNN)    (None, 128)               144512    
                                                                 
 dense_1 (Dense)             (None, 1000)              129000    
                                                                 
Total params: 273512 (1.04 MB)
Trainable params: 273512 (1.04 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [33]:
history = model.fit(X, Y, batch_size=32, epochs=19)

Epoch 1/19
1/1 [==============================] - 1s 1s/step - loss: 6.9024 - accuracy: 0.0000e+00
Epoch 2/19
1/1 [==============================] - 0s 10ms/step - loss: 6.8762 - accuracy: 0.0000e+00
Epoch 3/19
1/1 [==============================] - 0s 9ms/step - loss: 6.8498 - accuracy: 0.0714
Epoch 4/19
1/1 [==============================] - 0s 10ms/step - loss: 6.8229 - accuracy: 0.2143
Epoch 5/19
1/1 [==============================] - 0s 11ms/step - loss: 6.7953 - accuracy: 0.5000
Epoch 6/19
1/1 [==============================] - 0s 8ms/step - loss: 6.7666 - accuracy: 0.7143
Epoch 7/19
1/1 [==============================] - 0s 10ms/step - loss: 6.7366 - accuracy: 0.8929
Epoch 8/19
1/1 [==============================] - 0s 9ms/step - loss: 6.7050 - accuracy: 0.9286
Epoch 9/19
1/1 [==============================] - 0s 11ms/step - loss: 6.6714 - accuracy: 0.9643
Epoch 10/19
1/1 [==============================] - 0s 10ms/step - loss: 6.6353 - accuracy: 0.9643
Epoch 11/19
1/1 [=========

In [40]:
str_len = 20
data = tokenizer.texts_to_sequences([texts])[0]
def buildPhrase(texts, str_len):
  res = texts
  
  for i in range(str_len):
    x = keras.utils.to_categorical(data[i: i+inp_words], num_classes=maxWordsCount) # преобразуем в One-Hot-encoding
    inp = x.reshape(1, inp_words, maxWordsCount)
 
    pred = model.predict( inp ) # предсказываем OHE четвертого символа
    indx = pred.argmax(axis=1)[0]
    data.append(indx)
 
    res += " " + tokenizer.index_word[indx] # дописываем строку
 
  return res

In [41]:
res = buildPhrase("позитив добавляет годы", 10)
print(res)

1/1 [==============================] - 0s 26ms/step
позитив добавляет годы на проблемы которые возникли в понедельник подняться позитивно и верьте
